### ISSUE TITLE
Write a tutorial based on Victoria's QUBO training session

### ISSUE THREAD

**Issue by akoszegi** [dwavesystems/docs#81]
We've been getting feedback from beta testers about how difficult it is to go from running an example to crafting their own QUBO. They haven't found the help they need in the current Ocean documentation. 

@fionahanington and I were wondering about turning @vgoliber 's QUBO training material into documentation. The training session is on the silo drive: transfer\Fiona\Zoom recordings

**Comment by JoelPasvolsky** [comment]
Currently we have introductory examples here: https://docs.dwavesys.com/docs/latest/c_handbook_1.html. In general this book would be the place to look for such content. 
A good place for new material such as Victoria's could be here: https://docs.dwavesys.com/docs/latest/c_handbook_8.html
(The reason it would be in system docs rather than Ocean docs is that you're talking about mathematical reformulation rather than using Ocean tools to reformulate. Ocean just provides an entry point into mathematical reformulation, a single Getting Started example among four on the different entry points, and the rest is tools.)

**Comment by fionahanington** [comment]
Update: @vgoliber  is working on content to address this and it will end up in the sysdocs GSG. 
Tracked in Jira under https://jira.dwavesys.com/browse/DOC-148

**Comment by fionahanington** [comment]
I am closing this as it's being tracked in Jira and won't be part of ocean docs.
